### ISSUE TITLE
I want to see the list of preview of figure 

### ISSUE THREAD

**Issue by quenneylam** [erkin/ponysay#292]
There are so many ponies and i want to see all to choose my fav one. But it take time to try all by command . Thanks

**Comment by maandree** [comment]
You can use `ponysay-tool --browse /usr/share/ponysay/ponies/` and `ponysay-tool --browse /usr/share/ponysay/extraponies/`. Unfortunately it has to be update to because the list of ponies nowadays is too long that you cannot see the entire list.

You can also use `for p in /usr/share/ponysay/ponies/*.pony; do printf '\n\n\n\n\n%s\n' "$p" | rev | cut -d '/' -f 1 | rev | cut -d . -f 1; ponysay -of "$p"; done` or (and this one is bit harder to cancel) `for p in /usr/share/ponysay/ponies/*.pony; do printf '%s\n' "$p" | rev | cut -d '/' -f 1 | rev | cut -d . -f 1 | ponysay -f "$p"; done`.

**Comment by matthias4217** [comment]
There is also this : https://github.com/erkin/ponysay/issues/286

**Comment by quenneylam** [comment]
Thank you
